import Head from 'next/head';
import Footer from '../components/Footer/Footer';
import Header from '../components/Header/Header';

const LayoutMain = (props) => {
    const { children } = props;
    return (
        <div className='layout'>
            <Head>
                <title>JS Mastery Store</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <main className="mb-8">
                {children}
            </main>
            <footer>
                <Footer />
            </footer>
        </div>
    )
}

export default LayoutMain